### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in ${path}/node_modules/parse-duration/package.json

### ISSUE THREAD

**Issue by cressie176** [jkroso/parse-duration#20]
Hi. 
Thanks for parse-duration, I've been using it in loads of my libraries, however it's started failing under Node 14. I'm probably missing something obvious, getting the following error...

```
$ node --version
v14.2.0
$ node
Welcome to Node.js v14.2.0.
Type ".help" for more information.
> const parse = require('parse-duration');
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/steve/Development/cressie176/pipsqueak/node_modules/parse-duration/package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:596:11)
    at applyExports (internal/modules/cjs/loader.js:454:14)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at repl:1:15
    at Script.runInThisContext (vm.js:131:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Any ideas?

**Comment by dy** [comment]
Whoops, sorry for the error. Fixed in 0.4.1

**Comment by cressie176** [comment]
Same issue with 0.4.1 :(

**Comment by dy** [comment]
Try to clear cache, should work. Let me check

**Comment by dy** [comment]
Oh, wait, that's the different issue. Hold on.

**Comment by dy** [comment]
Ok, now is done in 0.4.2. Node ESM has implicit conventions, hence the issue.

**Comment by cressie176** [comment]
Working again now. Thanks for responding so quickl.
